# Memória do Gradle. A decompilação do Minecraft precisa de bastante.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Ambiente
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## GeckoLib (a 4.4.9 já foi testada no seu Zalith)
geckolib_version=4.4.9

## Mod
mod_id=froggydude
mod_name=Froggydude
mod_license=All Rights Reserved
mod_version=0.3.5
mod_group_id=com.froggydude
mod_authors=LM
mod_description=O FroggyDude com raiva. Fan-mod pessoal baseado nos vídeos do FroggyDude (youtube.com/@FroggyDudeMC).
